stages:
  - lint
  - test

include:
  - project: code0-tech/telescopium
    ref: build-branch
    file: ci-template.gitlab-ci.yml

docs:preview:
  stage: test
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  needs:
    - docs
  script:
    - >
      RESPONSE=$(curl
      -X POST
      --data '{
        "query":"query($fullPath: ID!, $iid: ID!, $bridgeJob: String!, $downstreamJob:String!) {
          project(fullPath: $fullPath) {
            pipeline(iid: $iid) {
              job(name: $bridgeJob) {
                downstreamPipeline {
                  job(name: $downstreamJob) { id }
                }
              }
            }
          }
        }","variables":{
          "fullPath":"$CI_PROJECT_PATH",
          "iid":"$CI_PIPELINE_IID",
          "bridgeJob":"docs",
          "downstreamJob":"build"
        }
      }'
      -H 'Content-Type: application/json'
      https://gitlab.com/api/graphql)
    - echo $RESPONSE
    - BUILD_JOB_ID=$(echo "$RESPONSE" | jq -r .data.project.pipeline.job.downstreamPipeline.job.id | awk -F '/' '{print $NF}')
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      echo "Documentation preview available at https://code0-tech.gitlab.io/-/telescopium/-/jobs/$BUILD_JOB_ID/artifacts/dist/index.html"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"

.bundle:
  image: ruby:3.2.2
  before_script:
    - bundle install --jobs $(nproc)

.rails:
  image: ghcr.io/code0-tech/build-images/ruby-3.2.2-postgres-16.1:5.1
  before_script:
    - source ~/.asdf/asdf.sh
    - bundle config build.pg --with-pg-config=$(asdf where postgres)/bin/pg_config
    - !reference [.bundle, before_script]
  services:
    - postgres:16.1
  variables:
    POSTGRES_DB: sagittarius_test
    POSTGRES_USER: sagittarius
    POSTGRES_PASSWORD: sagittarius
    SAGITTARIUS_DATABASE_HOST: postgres
    SAGITTARIUS_DATABASE_PORT: '5432'
    RAILS_ENV: test

rubocop:
  extends:
    - .bundle
  stage: lint
  script:
    - bundle exec rubocop

graphql_docs:
  extends:
    - .rails
  stage: lint
  script:
    - bundle exec rake graphql:compile_docs
    - git diff --exit-code

rspec:
  extends:
    - .rails
  stage: test
  variables:
    FPROF: '1'
  script:
    - bundle exec rspec --format doc --format RspecJunitFormatter --out rspec.xml
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      echo "Coverage report available at https://code0-tech.gitlab.io/-/sagittarius/-/jobs/$CI_JOB_ID/artifacts/tmp/coverage/index.html"
      echo "Test summary available at https://gitlab.com/code0-tech/sagittarius/-/pipelines/$CI_PIPELINE_ID/test_report"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
  artifacts:
    expire_in: 7 days
    paths:
      - tmp/coverage/index.html
      - tmp/coverage/assets/
    reports:
      junit:
        - rspec.xml

db:migrate:
  extends:
    - .rails
  stage: test
  script:
    - bundle exec rake db:migrate:reset
    - git diff --exit-code

db:rollback-and-migrate:
  extends:
    - .rails
  stage: test
  allow_failure: true
  script:
    - bundle exec rake db:create db:schema:load
    - bundle exec rake db:migrate VERSION=20231203194307
    - bundle exec rake db:migrate
    - git diff --exit-code
