version: '3.9'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: "sagittarius"
      POSTGRES_PASSWORD: "sagittarius"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data/
      - ./tooling/init-dev-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  valkey:
    image: valkey/valkey:8.1-alpine
    profiles:
      - runtime
    restart: unless-stopped
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    profiles:
      - runtime
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"

  aquila:
    image: ghcr.io/code0-tech/reticulum/ci-builds/aquila:1869897590
    profiles:
      - runtime
    network_mode: host
    environment:
      MODE: dynamic
      ENVIRONMENT: development
      REDIS_URL: redis://localhost:6380
      BACKEND_URL: http://localhost:50051
      RUNTIME_TOKEN: development_runtime_token
    restart: unless-stopped

  draco-rest:
    image: ghcr.io/code0-tech/reticulum/ci-builds/draco:1869897590-rest
    profiles:
      - runtime
    network_mode: host
    environment:
      PORT: "8081"
      REDIS_URL: redis://localhost:6380
      RABBITMQ_URL: amqp://localhost:5673
      AQUIlA_URL: http://localhost:8083
      IS_STATIC: "false"
    restart: unless-stopped

  taurus:
    image: ghcr.io/code0-tech/reticulum/ci-builds/taurus:1869897590
    profiles:
      - runtime
    network_mode: host
    environment:
      ENVIRONMENT: "development"
      MODE: "dynamic"
      RABBITMQ_URL: "amqp://localhost:5673"
      AQUILA_URL: "http://localhost:8083"
    restart: unless-stopped

volumes:
  database:
