# frozen_string_literal: true

class UserMailer < ApplicationMailer
  COMPANY_NAME = 'Code0'
  WEB_URL = 'https://codezero.build'
  # Both tokens are generated with `expires_in: 15.minutes` (see User#generates_token_for).
  LINK_VALIDITY = 15.minutes
  # Email clients cannot resolve relative image paths, so the logo is referenced on the public web
  # host. The same asset is kept in public/static for the local mailer previews.
  LOGO_URL = "#{WEB_URL}/api/media/file/Logo-03%20copy-cropped%20copy.svg".freeze

  # The HTML templates are complete, self-contained documents (generated by react-email, see
  # tooling/mails), each with their own <html>/<head>/<body>. Wrapping them in the shared "mailer"
  # layout would nest a second <html>/<head>/<body> inside the layout's <body>, so UserMailer
  # renders without a layout instead.
  layout false

  def email_verification
    assign_common
    @verification_url = "#{WEB_URL}/verify?code=#{CGI.escape(params[:verification_code])}"

    mail(to: @user.email, subject: 'Email verification')
  end

  def password_reset
    assign_common
    @reset_url = "#{WEB_URL}/password-forgot?code=#{CGI.escape(params[:verification_code])}"

    mail(to: @user.email, subject: 'Password reset')
  end

  private

  def assign_common
    @user = params[:user]
    @company_name = COMPANY_NAME
    @user_name = @user.firstname.presence || @user.username
    @account_name = @user.username
    @email = @user.email
    @link_expires_in = "#{LINK_VALIDITY.in_minutes.to_i} minutes"
    @support_email = support_email
    @logo_url = LOGO_URL
  end

  def support_email
    Mail::Address.new(Sagittarius::Configuration.config.dig(:rails, :mailer, :from)).address
  end
end
