# frozen_string_literal: true

module Types
  class AIGenerationReferencePathType < Types::BaseObject
    description 'Represents a reference path generated by AI.'

    field :array_index, GraphQL::Types::Int,
          null: true,
          description: 'The generated reference array index.'
    field :path, String,
          null: true,
          description: 'The generated reference path.'
  end
end
