# frozen_string_literal: true

module Types
  class AIGenerationReferenceValueType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a reference value generated by AI.'

    field :input_index, GraphQL::Types::Int,
          null: true,
          description: 'The generated referenced input index.'
    field :node_function_id, Types::GlobalIdType[::NodeFunction],
          null: true,
          description: 'The generated referenced node function ID.'
    field :parameter_index, GraphQL::Types::Int,
          null: true,
          description: 'The generated referenced parameter index.'
    field :reference_path, [Types::AIGenerationReferencePathType],
          null: false,
          description: 'The generated reference paths.'

    def node_function_id
      generated_global_id(object[:node_function_id], ::NodeFunction)
    end
  end
end
