# frozen_string_literal: true

module Types
  class AIGenerationFlowType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a flow generated by AI.'

    field :name, String, null: true, description: 'Generated flow name.'
    field :nodes, [Types::AIGenerationNodeFunctionType],
          null: false,
          description: 'Generated node functions of the flow.'
    field :settings, [Types::AIGenerationFlowSettingType],
          null: false,
          description: 'Generated flow settings.'
    field :starting_node_id, Types::GlobalIdType[::NodeFunction],
          null: true,
          description: 'Generated starting node ID.'
    field :type, String, null: true, description: 'Generated flow type identifier.'

    def starting_node_id
      generated_global_id(object[:starting_node_id], ::NodeFunction)
    end
  end
end
