# frozen_string_literal: true

module Types
  class AIGenerationNodeFunctionType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a node function generated by AI.'

    field :definition_source, String, null: true, description: 'The generated node function definition source.'
    field :function_identifier, String, null: true, description: 'The generated runtime function identifier.'
    field :id, Types::GlobalIdType[::NodeFunction], null: false, description: 'Generated global ID for this node.'
    field :next_node_id, Types::GlobalIdType[::NodeFunction],
          null: true,
          description: 'Generated next node ID.'
    field :parameters, [Types::AIGenerationNodeParameterType],
          null: false,
          description: 'Generated node parameters.'

    def id
      generated_global_id(object[:id], ::NodeFunction)
    end

    def next_node_id
      generated_global_id(object[:next_node_id], ::NodeFunction)
    end
  end
end
