# frozen_string_literal: true

module Types
  class AIGenerationSubFlowValueType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a sub-flow value generated by AI.'

    field :function_identifier, String,
          null: true,
          description: 'The generated sub-flow function identifier.'
    field :settings, [Types::AIGenerationSubFlowSettingType],
          null: false,
          description: 'The generated sub-flow settings.'
    field :signature, String,
          null: true,
          description: 'The generated sub-flow signature.'
    field :starting_node_id, Types::GlobalIdType[::NodeFunction],
          null: true,
          description: 'The generated sub-flow starting node ID.'

    def starting_node_id
      generated_global_id(object[:starting_node_id], ::NodeFunction)
    end
  end
end
