# frozen_string_literal: true

module Types
  class AIGenerationNodeValueType < Types::BaseObject
    description 'Represents a node value generated by AI.'

    field :literal_value, GraphQL::Types::JSON,
          null: true,
          description: 'The generated literal value.'
    field :reference_value, Types::AIGenerationReferenceValueType,
          null: true,
          description: 'The generated reference value.'
    field :sub_flow_value, Types::AIGenerationSubFlowValueType,
          null: true,
          description: 'The generated sub-flow value.'
  end
end
