# frozen_string_literal: true

module Types
  class AIGenerationNodeParameterType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a node parameter generated by AI.'

    field :cast, String, null: true, description: 'The generated cast applied to the parameter.'
    field :id, Types::GlobalIdType[::NodeParameter],
          null: false,
          description: 'Generated global ID for this parameter.'
    field :parameter_identifier, String, null: true, description: 'The generated runtime parameter identifier.'
    field :value, Types::AIGenerationNodeValueType, null: false, description: 'The generated parameter value.'

    def id
      generated_global_id(object[:id], ::NodeParameter)
    end
  end
end
