# frozen_string_literal: true

module Types
  class AIGenerationFlowSettingType < Types::BaseObject
    include Types::Concerns::GeneratedGlobalId

    description 'Represents a flow setting generated by AI.'

    field :cast, String, null: true, description: 'The generated cast applied to the flow setting.'
    field :flow_setting_id, String, null: true, description: 'The generated flow setting identifier.'
    field :id, Types::GlobalIdType[::FlowSetting], null: false, description: 'Generated global ID for this setting.'
    field :value, GraphQL::Types::JSON, null: true, description: 'The generated value of the flow setting.'

    def id
      generated_global_id(object[:id], ::FlowSetting)
    end
  end
end
