# frozen_string_literal: true

module Types
  module Ai
    class GenerationLiteralValueType < Types::BaseObject
      description 'Represents a literal value generated by AI.'

      field :value, GraphQL::Types::JSON,
            null: true,
            description: 'The generated literal value as JSON.'

      def value
        object.key?(:value) ? object[:value] : object['value']
      end
    end
  end
end
