# frozen_string_literal: true

module Types
  module Ai
    class GenerationNodeParameterType < Types::BaseObject
      description 'Represents a node parameter generated by AI.'

      field :cast, String, null: true, description: 'The generated cast applied to the parameter.'
      field :id, Types::GlobalIdType[::NodeParameter],
            null: false,
            description: 'Generated global ID for this parameter.'
      # rubocop:disable GraphQL/ExtractType -- generated parameters mirror the flow input shape.
      field :parameter_definition_id, Types::GlobalIdType[::ParameterDefinition],
            null: true,
            description: 'Resolved parameter definition ID for the generated parameter.'
      field :parameter_identifier, String, null: true, description: 'The generated runtime parameter identifier.'
      # rubocop:enable GraphQL/ExtractType
      field :value, Types::Ai::GenerationNodeValueType, null: false, description: 'The generated parameter value.'

      def id
        Sagittarius::Utils.generated_global_id(object[:id], ::NodeParameter)
      end

      def parameter_definition_id
        Sagittarius::Utils.generated_global_id(object[:parameter_definition_id], ::ParameterDefinition)
      end
    end
  end
end
