# frozen_string_literal: true

module Types
  module Ai
    class GenerationNodeFunctionType < Types::BaseObject
      description 'Represents a node function generated by AI.'

      field :definition_source, String, null: true, description: 'The generated node function definition source.'
      # rubocop:disable GraphQL/ExtractType -- generated nodes mirror the flow input shape.
      field :function_definition, Types::FunctionDefinitionType,
            null: true,
            description: 'Resolved function definition for the generated node.'
      field :function_identifier, String, null: true, description: 'The generated runtime function identifier.'
      # rubocop:enable GraphQL/ExtractType
      field :id, Types::GlobalIdType[::NodeFunction], null: false, description: 'Generated global ID for this node.'
      field :next_node_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'Generated next node ID.'
      field :parameters, [Types::Ai::GenerationNodeParameterType],
            null: false,
            description: 'Generated node parameters.'

      def id
        Sagittarius::Utils.generated_global_id(object[:id], ::NodeFunction)
      end

      def next_node_id
        Sagittarius::Utils.generated_global_id(object[:next_node_id], ::NodeFunction)
      end
    end
  end
end
