# frozen_string_literal: true

module Types
  module Ai
    class GenerationInputTypeType < Types::BaseObject
      description 'Represents an input type reference generated by AI.'

      field :input_index, GraphQL::Types::Int,
            null: true,
            description: 'The generated referenced input index.'
      field :node_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'The generated referenced node ID.'
      field :parameter_index, GraphQL::Types::Int,
            null: true,
            description: 'The generated referenced parameter index.'

      def node_id
        Sagittarius::Utils.generated_global_id(object[:node_id], ::NodeFunction)
      end
    end
  end
end
