# frozen_string_literal: true

module Types
  module Ai
    class GenerationInlineReferenceValueType < Types::BaseObject
      description 'Represents an inline reference generated by AI, addressable via `${signature}`.'

      field :signature, String,
            null: true,
            description: 'The key addressed via `${signature}`.'
      field :value, Types::Ai::GenerationNodeValueType,
            null: true,
            description: 'The generated value this reference resolves to.'
    end
  end
end
