# frozen_string_literal: true

module Types
  module Ai
    class GenerationSubFlowValueType < Types::BaseObject
      description 'Represents a sub-flow value generated by AI.'

      field :function_identifier, String,
            null: true,
            description: 'The generated sub-flow function identifier.'
      field :settings, [Types::Ai::GenerationSubFlowSettingType],
            null: false,
            description: 'The generated sub-flow settings.'
      field :signature, String,
            null: true,
            description: 'The generated sub-flow signature.'
      field :starting_node_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'The generated sub-flow starting node ID.'

      def starting_node_id
        Sagittarius::Utils.generated_global_id(object[:starting_node_id], ::NodeFunction)
      end
    end
  end
end
