# frozen_string_literal: true

module Types
  module Ai
    class GenerationNodeValueType < Types::BaseObject
      description 'Represents a node value generated by AI.'

      field :literal_value, GraphQL::Types::JSON,
            null: true,
            description: 'The generated literal value.'
      field :reference_value, Types::Ai::GenerationReferenceValueType,
            null: true,
            description: 'The generated reference value.'
      # rubocop:disable GraphQL/ExtractType -- keep both gRPC and existing frontend names available.
      field :sub_flow, Types::Ai::GenerationSubFlowValueType,
            null: true,
            description: 'The generated sub-flow value, matching the gRPC field name.'
      field :sub_flow_value, Types::Ai::GenerationSubFlowValueType,
            null: true,
            description: 'The generated sub-flow value.'
      # rubocop:enable GraphQL/ExtractType
    end
  end
end
