# frozen_string_literal: true

module Types
  module Ai
    class GenerationFlowSettingType < Types::BaseObject
      description 'Represents a flow setting generated by AI.'

      field :cast, String, null: true, description: 'The generated cast applied to the flow setting.'
      field :flow_type_setting, Types::FlowTypeSettingType,
            null: false,
            description: 'Resolved flow type setting for the generated setting.'
      field :flow_setting_identifier, String,
            null: false,
            description: 'The resolved identifier of the generated flow setting.'
      field :id, Types::GlobalIdType[::FlowSetting], null: false,
                                                     description: 'Generated global ID for this setting.'
      field :value, GraphQL::Types::JSON, null: true, description: 'The generated value of the flow setting.'

      def id
        Sagittarius::Utils.generated_global_id(object[:id], ::FlowSetting)
      end
    end
  end
end
