# frozen_string_literal: true

module Types
  module Ai
    class GenerationNodeParameterType < Types::BaseObject
      description 'Represents a node parameter generated by AI.'

      field :cast, String, null: true, description: 'The generated cast applied to the parameter.'
      field :id, Types::GlobalIdType[::NodeParameter],
            null: false,
            description: 'Generated global ID for this parameter.'
      field :parameter_definition, Types::ParameterDefinitionType,
            null: true,
            description: 'Resolved parameter definition for the generated parameter.'
      field :value, Types::Ai::GenerationNodeValueType, null: true, description: 'The generated parameter value.'

      def id
        Sagittarius::Utils.generated_global_id(object[:id], ::NodeParameter)
      end
    end
  end
end
