# frozen_string_literal: true

module Types
  module Ai
    class GenerationSubFlowSettingType < Types::BaseObject
      description 'Represents a sub-flow setting generated by AI.'

      field :default_value, GraphQL::Types::JSON,
            null: true,
            description: 'The generated default value of the sub-flow setting.'
      field :hidden, Boolean,
            null: true,
            description: 'Whether the generated sub-flow setting is hidden.'
      field :identifier, String,
            null: true,
            description: 'The generated sub-flow setting identifier.'
      field :optional, Boolean,
            null: true,
            description: 'Whether the generated sub-flow setting is optional.'
    end
  end
end
