# frozen_string_literal: true

module Types
  module Ai
    class GenerationReferenceValueType < Types::BaseObject
      description 'Represents a reference value generated by AI.'

      field :id, Types::GlobalIdType[::ReferenceValue],
            null: false,
            description: 'Global ID of this ReferenceValue'
      # rubocop:disable GraphQL/ExtractType
      field :input_index, GraphQL::Types::Int,
            null: true,
            description: 'The index of the referenced input'
      field :input_type_identifier, GraphQL::Types::String,
            null: true,
            description: 'The identifier of the input type'
      # rubocop:enable GraphQL/ExtractType
      field :node_function_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'The referenced value unless referencing the flow input.'
      field :parameter_index, GraphQL::Types::Int,
            null: true,
            description: 'The index of the referenced parameter'
      field :reference_path, [Types::Ai::GenerationReferencePathType],
            null: false,
            description: 'The paths associated with this reference value.'

      def id
        Sagittarius::Utils.generated_global_id(object[:id] || object['id'], ::ReferenceValue)
      end

      def node_function_id
        Sagittarius::Utils.generated_global_id(object[:node_function_id] || object['node_function_id'], ::NodeFunction)
      end
    end
  end
end
