# frozen_string_literal: true

module Types
  module Ai
    class GenerationFlowType < Types::BaseObject
      description 'Represents a flow generated by AI.'

      field :name, String, null: false, description: 'Generated flow name.'
      field :nodes, [Types::Ai::GenerationNodeFunctionType],
            null: false,
            description: 'Generated node functions of the flow.'
      field :settings, [Types::Ai::GenerationFlowSettingType],
            null: true,
            description: 'Generated flow settings.'
      field :starting_node_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'Generated starting node ID.'
      field :type, Types::FlowTypeType, null: false, description: 'Resolved generated flow type.'

      def starting_node_id
        Sagittarius::Utils.generated_global_id(object[:starting_node_id], ::NodeFunction)
      end
    end
  end
end
