# frozen_string_literal: true

module Types
  module Ai
    class GenerationReferenceValueType < Types::BaseObject
      description 'Represents a reference value generated by AI.'

      field :flow_input, Boolean,
            null: true,
            description: 'Whether this reference targets the flow input, matching the gRPC field.'
      # rubocop:disable GraphQL/ExtractType -- keep both gRPC and existing frontend names available.
      field :input_index, GraphQL::Types::Int,
            null: true,
            description: 'The generated referenced input index.'
      field :input_type, Types::Ai::GenerationInputTypeType,
            null: true,
            description: 'The generated input type reference, matching the gRPC field.'
      field :node_function_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'The generated referenced node function ID.'
      field :node_id, Types::GlobalIdType[::NodeFunction],
            null: true,
            description: 'The generated referenced node ID, matching the gRPC field.'
      # rubocop:enable GraphQL/ExtractType
      field :parameter_index, GraphQL::Types::Int,
            null: true,
            description: 'The generated referenced parameter index.'
      field :reference_path, [Types::Ai::GenerationReferencePathType],
            null: false,
            description: 'The generated reference paths.'

      def node_function_id
        Sagittarius::Utils.generated_global_id(object[:node_function_id] || object['node_function_id'], ::NodeFunction)
      end

      def node_id
        Sagittarius::Utils.generated_global_id(object[:node_id] || object['node_id'], ::NodeFunction)
      end
    end
  end
end
