# frozen_string_literal: true

module Types
  module Ai
    class GenerationNodeValueType < Types::BaseUnion
      description 'Represents a node value generated by AI.'

      possible_types Types::Ai::GenerationLiteralValueType,
                     Types::Ai::GenerationReferenceValueType,
                     Types::Ai::GenerationSubFlowValueType

      def self.resolve_type(object, _context)
        generated_value_type = object[:generated_value_type] || object['generated_value_type'] if object.is_a?(Hash)

        case generated_value_type&.to_sym
        when :reference_value
          Types::Ai::GenerationReferenceValueType
        when :sub_flow_value
          Types::Ai::GenerationSubFlowValueType
        else
          Types::Ai::GenerationLiteralValueType
        end
      end
    end
  end
end
